### ISSUE TITLE
How to adapt the current init file to use listenbrainz?

### ISSUE THREAD

**Issue by alscaldas** [vjeranc/cmus-status-scrobbler#1]
Hello,

I've just found and installed this cmus audio player to test (I've been using mpd for a while now) and one of the first things I searched first for was a scrobbler. Yours seems to be very useful and works like a charm with both Last.fm and Libre.fm, but I can't successfully configure it to run with Listenbrainz.

That's what I did so far on the file cmus_status_scrobbler.ini, but isn't working:

`[listenbrainz]
now_playing = yes
api_url = http://proxy.listenbrainz.org/
api_key = my-listenbrainz-token
username = my-listenbrainz-user`

Could you please point me in the right direction?

**Comment by vjeranc** [comment]
I think you need `https://api.listenbrainz.org` as the `API_URL`. It's the latest Last FM api, not the audioscrobbler v1.2.

**Comment by alscaldas** [comment]
> I think you need `https://api.listenbrainz.org` as the `API_URL`. It's the latest Last FM api, not the audioscrobbler v1.2.

Then I believe I'm doing something wrong. I've just tested with the url you suggested (in fact I'd already tried this one before asking), but it doesn't work.

Here is my complete cmus_status_scrobbler.ini:

```
[global]
now_playing = no
api_key = 3f427fc05464646ddf068ca2b02fbb6c
shared_secret = 9b57c32410ec5b068a4f39715a85ef79

[lastfm]
now_playing = yes
api_url = https://ws.audioscrobbler.com/2.0/
auth_url = https://www.last.fm/api/auth/
session_key = my-lastfm-session-key
username = my-lastfm-username

[librefm]
now_playing = yes
api_url = https://libre.fm/2.0/
auth_url = https://libre.fm/api/auth/
session_key = my-librefm-session-key
username = my-librefm-username

[listenbrainz]
now_playing = yes
api_url = https://api.listenbrainz.org
api_key = my-listenbrainz-token (the one I get from [Listenbrainz profile](https://listenbrainz.org/profile). Is that the correct data to insert here? what about "auth_url" Is there one for the listenbrainz code block?)
username = my-listenbrainz-username
```


And here is the error log I get:

```
INFO:root:Scrobbling lastfm   
INFO:root:{'artist': 'Anitta', 'track': 'Vai malandra', 'album': 'Vai malandra', 'duration': '328', 'sk': 'oDh93tYW
SqtKh6DVsumUDi_i66HTnbED', 'api_key': '3f427fc05464646ddf068ca2b02fbb6c', 'method': 'track.updateNowPlaying', 'api_
sig': 'e18f666fc0d6afdeab7e745d6c137320', 'format': 'json'}
INFO:root:{"nowplaying":{"artist":{"corrected":"0","#text":"Anitta"},"track":{"corrected":"0","#text":"Vai malandra
"},"ignoredMessage":{"code":"0","#text":""},"albumArtist":{"corrected":"0","#text":""},"album":{"corrected":"0","#t
ext":"Vai malandra"}}}
INFO:root:Scrobbling librefm  
INFO:root:{'artist': 'Anitta', 'track': 'Vai malandra', 'album': 'Vai malandra', 'duration': '328', 'sk': '02413076
3217bc7a79d431c577ebaac7', 'api_key': 'my-lastfm-api-key', 'method': 'track.updateNowPlaying', 'api_
sig': '894934140890b63b7a8bee147077b9f5', 'format': 'json'}
INFO:root:{"nowplaying":{"track":{"#text":"Vai malandra","corrected":"0"},"artist":{"#text":"Anitta","corrected":"0
"},"album":{"#text":"Vai malandra","corrected":"0"},"albumArtist":{"#text":"","corrected":"0"},"ignoredMessage":{"#
text":"","code":"0"}}}
INFO:root:Scrobbling listenbrainz
INFO:root:{'artist': 'Anitta', 'track': 'Vai malandra', 'album': 'Vai malandra', 'duration': '328', 'api_key': 'my-listenbrainz-token', 'method': 'track.updateNowPlaying', 'api_sig': '25714f915a8bc668b82d4e2d958be0d
5', 'format': 'json'}
ERROR:root:Ignoring this error.
Traceback (most recent call last):
  File "/home/myuser/.local/bin/cmus_status_scrobbler.py", line 113, in send_req
    with ur.urlopen(api_req, up.urlencode(params).encode('utf-8')) as f:
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
```

The scrobbling works for both librefm and lastfm, but not listenbrainz.

Thanks for taking the time to help me with this.

**Comment by vjeranc** [comment]
Ok, looks like `api_url = https://listenbrainz.org/2.0/` and `auth_url = https://listenbrainz.org/api/auth/` works better for auth. But it looks like `format=json` does not work for `auth.gettoken` ( I get a server error `Internal server error: OrderedDict mutated during iteration` )

`https://listenbrainz.org/2.0/?api_key=API_KEY&method=auth.gettoken&format=json`
When `format=json` is removed then the token gets returned.

`https://api.listenbrainz.org/2.0/?api_key=8NNTLbF555qWbAxxEEOcR2DikXsVHmHa&method=auth.gettoken` works too.

Similarly
`https://listenbrainz.org/api/auth/?api_key=API_KEY&token=TOKEN_FROM_LINK_ABOVE`

works
```
A legacy last.fm application wishes to have access to your account. If you approve it, this application will be able to submit listens on your behalf. Please consider asking the developers of your application to add support to submit directly to ListenBrainz.
Allow access? 
```
but when you click on "Yes please" button 

I get ` Either this token is already used or invalid. Please try again. `.

So looks like something broke with the last fm api. Similarily the `/api/auth` completely fails for `api.listenbrainz.org` because OAuth does not work (user can't be logged in into their listenbrainz account).

So, not sure what happened there in the meantime.

I guess I could use their non-LastFM api to scrobble instead.

**Comment by vjeranc** [comment]
Just to summarize, it means you cannot currently get the session key so that you can submit the scrobbles.

**Comment by vjeranc** [comment]
Looks like their tracker already caught the error while I was trying things out.

https://tickets.metabrainz.org/browse/LB-994

**Comment by alscaldas** [comment]
And what do you recommend to do in such situation? Delete all data and run the script with the `--auth` parameter again? I'm asking because I've tried it and it didn't work.

**Comment by alscaldas** [comment]
I'm so sorry. I was reading your posts and accidentally closed it.

**Comment by vjeranc** [comment]
Yeah, they have a few bugs and until then one cannot authenticate.

**Comment by vjeranc** [comment]
I managed to go around the errors. The changes are in `listenbrainz-workaround` branch. It parses the xml output for auth, and it looks like they haven't properly sanitized their outputs.

For example, auth.gettoken will return `b'40charactersLongToken'` as token instead of just the 40 characters.
Similarly, `auth.getsession` returns `\xlongsessiontoken` as session but there should be no `\x`.

I do not have time to figure out how to make the scrobbling work, I've tried with the session value and got a `BAD REQUEST` error.

**Comment by vjeranc** [comment]
Looks like scrobbling works now too.

**Comment by vjeranc** [comment]
I merged the changes to `main` branch.

**Comment by vjeranc** [comment]
There's a new `xml_auth` option in `.ini` so add it for listenbrainz. You should successfully authenticate then through musicbrainz (give permission).

After that scrobbling/now-playing should work.

**Comment by vjeranc** [comment]
It looks like the "My Listens" section on listenbrainz.org is very slow now. I do not know if the scrobbling service is currently stable. Check the logs of the scrobbler and see if something fails in the meanwhile. I guess you could import the scrobbles if some get dropped by listenbrainz.

**Comment by alscaldas** [comment]
Thank you very much for your patience and, again, for taking the time to look into this issue. Sorry for the delay (we have different timezones, I believe) and I also was testing.

I got no errors after the changes you made. But it apparently doesn't scrobble either. The weird part is that the log apparently shows the current song I'm playing on both Lastfm and Librefm, but the previous song on Listenbrainz. And even so it doens't update my Listenbrainz's "My Listen" section. 

I'm attaching part of the log, if it helps somehow.

```
INFO:root:Sending now playing for lastfm
INFO:root:{'artist': 'U2', 'track': 'A Sort of Homecoming', 'album': 'The Unforgettable Fire', 'trackNumber': '1', 'duration': '329', 'mbid': 'c40992e4-cd3b-4ff3-98d6-fffb0c236a5c', 'sk': 'cD8GewWE_h0vNkTZ5TRTcFenjDPzX-Yc', 'api_key': '3f427fc05464646ddf068ca2b02fbb6c', 'method': 'track.updateNowPlaying', 'api_sig': 'feedc92d29a4667930088f92ce6f489f', 'format': 'json'}
INFO:root:{"nowplaying":{"artist":{"corrected":"0","#text":"U2"},"track":{"corrected":"0","#text":"A Sort of Homecoming"},"ignoredMessage":{"code":"0","#text":""},"albumArtist":{"corrected":"0","#text":""},"album":{"corrected":"0","#text":"The Unforgettable Fire"}}}
INFO:root:Scrobbling previous tracks for lastfm
INFO:root:Sending now playing for librefm
INFO:root:{'artist': 'U2', 'track': 'A Sort of Homecoming', 'album': 'The Unforgettable Fire', 'trackNumber': '1', 'duration': '329', 'mbid': 'c40992e4-cd3b-4ff3-98d6-fffb0c236a5c', 'sk': '6a1bda3b6d3d143bec1c927b0c31a2f9', 'api_key': '3f427fc05464646ddf068ca2b02fbb6c', 'method': 'track.updateNowPlaying', 'api_sig': '76e8de0b19ab405b3482f2eb334d07a8', 'format': 'json'}
INFO:root:{"nowplaying":{"track":{"#text":"A Sort of Homecoming","corrected":"0"},"artist":{"#text":"U2","corrected":"0"},"album":{"#text":"The Unforgettable Fire","corrected":"0"},"albumArtist":{"#text":"","corrected":"0"},"ignoredMessage":{"#text":"","code":"0"}}}
INFO:root:Scrobbling previous tracks for librefm
INFO:root:Sending now playing for listenbrainz
INFO:root:Scrobbling previous tracks for listenbrainz
INFO:root:{'sk': '14f1a3fe-1bdd-4029-b6a4-41f88521d727', 'artist[0]': 'ABBA', 'track[0]': 'Mamma Mia', 'timestamp[0]': '1636307528', 'album[0]': 'ABBA', 'trackNumber[0]': '1', 'duration[0]': '212', 'artist[1]': 'ABBA', 'track[1]': 'Hey, Hey, Helen', 'timestamp[1]': '1636307740', 'album[1]': 'ABBA', 'trackNumber[1]': '2', 'duration[1]': '197', 'artist[2]': 'ABBA', 'track[2]': 'Tropical Loveland', 'timestamp[2]': '1636307938', 'album[2]': 'ABBA', 'trackNumber[2]': '3', 'duration[2]': '186', 'artist[3]': 'Anitta & J Balvin', 'track[3]': 'Downtown', 'timestamp[3]': '1636308364', 'album[3]': 'Downtown', 'trackNumber[3]': '1', 'mbid[3]': 'b470aed8-b246-46a6-b8a2-b7d0a3ea9618', 'duration[3]': '193', 'artist[4]': 'Belchior', 'track[4]': 'Medo De Avião', 'timestamp[4]': '1636308785', 'album[4]': 'Medo De Avião', 'trackNumber[4]': '1', 'duration[4]': '149', 'artist[5]': 'Belchior', 'track[5]': 'Retórica Sentimental', 'timestamp[5]': '1636308933', 'album[5]': 'Medo De Avião', 'trackNumber[5]': '2', 'duration[5]': '185', 'api_key': '3f427fc05464646ddf068ca2b02fbb6c', 'method': 'track.scrobble', 'api_sig': '6ca49e7aa190fc68ca2141bd64decbb4', 'format': 'json'}
```

**Comment by vjeranc** [comment]
No problem.

Looks like `format=json` is not reliable. I changed the implementation again, replaced `xml_auth` with `format_xml` and use xml result everywhere. Seems to work fine with listenbrainz now.

**Comment by alscaldas** [comment]
@vjeranc 

Now it works!

In fact it took me some time because I believe the urls referring to the listenbrainz block of the ini file should be "org" instead of "com". As soon as I changed them it begun scrobbling as expected.

```
[listenbrainz]
now_playing = yes
api_url = https://listenbrainz.org/2.0/
auth_url = https://listenbrainz.org/api/auth/
format_xml = yes
session_key = my-session-key
username = my-username
```
I guess it's all working now as expected.

Thank you very much for your invaluable help. I'm really enjoying a lot this cmus player and this scrobbler project of yours is very nice!
