### ISSUE TITLE
Confusing "How to use?"

### ISSUE THREAD

**Issue by BoostCookie** [vjeranc/cmus-status-scrobbler#10]
I'm talking about the lines
https://github.com/vjeranc/cmus-status-scrobbler/blob/e970e4d293e9839649f0ab4db648ff2d92e24d0a/README.md?plain=1#L24-L27

Why does it talk about a `status_display_program.sh`? Where is this shell script? In my opinion it should say something like

> Tell cmus to use the scrobbler
> ```
> :set status_display_program=path/to/cmus_status_scrobbler.py
> ```

**Comment by vjeranc** [comment]
Usually people use `cmus` with a variety of display programs, one of them being `cmus_status_scrobbler.py`.

But yeah, setting `cmus_status_scrobbler.py` as your only status processing program is also possible.

**Comment by vjeranc** [comment]
But yeah, I added this as the default option now in the README

**Comment by BoostCookie** [comment]
Thanks. And also thanks for this nice script.

**Comment by BoostCookie** [comment]
I've added it to the AUR, btw.
https://aur.archlinux.org/packages/cmus-status-scrobbler-git

**Comment by GUUser91** [comment]
I want to give a heads up for those using cmus-status-scrobbler in the termux app and have android 14.
This command below no longer works in android 14. Or at least it doesn't on OnePlus Pad.
>:set status_display_program=path/to/cmus_status_scrobbler.py

So create a bash script called status_display_program.sh. Add these lines
>#!/bin/sh

>/data/data/com.termux/files/home/.config/cmus/cmus_status_scrobbler.py "$@" &

Execute both the .py and .sh files
>chmod +rx status_display_program.sh

>chmod +rx cmus_status_scrobbler.py

Invoke
>:set status_display_program=/data/data/com.termux/files/home/.config/cmus/status_display_program.sh

in cmus

**Comment by vjeranc** [comment]
@GUUser91 Thanks, I've added the Termux section under "How to use?".

**Comment by GUUser91** [comment]
I want to give another heads up. You need to change the location of the tmp folder in order for cmus-status-scrobbler to work in termux. Edit the cmus-status-scrobbler.py file with a text editor like micro and vim.
>micro cmus_status_scrobbler.py

Change
>/tmp/cmus_scrobbler.log

to
>/data/data/com.termux/files/usr/tmp/cmus_scrobbler.log
