### ISSUE TITLE
Change python in shebang to python3?

### ISSUE THREAD

**Issue by beesarefriends** [vjeranc/cmus-status-scrobbler#12]
Ubuntu/derivatives and some other linux distros (I have no idea about windows etc) tend to not have a 'python' command and instead rely on explicitly using 'python2' or 'python3.' I'm not sure if there would be a downside, but changing from `#!/usr/bin/env python` to `#!/usr/bin/env python3,` this is only particularly an issue when using as the only status display program, as if its in another script python3 can be specifically called.

## Environment
Python version: Python 3.10.12
cmus version: cmus v2.12.0-2-ga15a9e0

**Comment by vjeranc** [comment]
Yep, I agree.
