### ISSUE TITLE
Problems with logging seem to prevent anything from happening

### ISSUE THREAD

**Issue by AlbeyAmakiir** [vjeranc/cmus-status-scrobbler#3]
I tried running `python3.8 cmus_status_scrobbler.py --auth`, but nothing was happening at all. My logs just have this repeated, once per attempt:

```
ERROR:root:Error happened
Traceback (most recent call last):
  File "cmus_status_scrobbler.py", line 445, in <module>
    main()
  File "cmus_status_scrobbler.py", line 428, in main
    setup_logging(args.log_path or conf['global'].get('log_path'))
  File "cmus_status_scrobbler.py", line 356, in setup_logging
    logging.basicConfig(filename=log_path or '/tmp/cmus_scrobbler.log',
  File "/usr/lib64/python3.8/logging/__init__.py", line 2009, in basicConfig
    raise ValueError('Unrecognised argument(s): %s' % keys)
ValueError: Unrecognised argument(s): encoding
```

Changing the log target file merely put this same error into a different log file.

**Comment by vjeranc** [comment]
It's a Python version issue. I guess I used a too new feature, the `encoding` option of `basicConfig` in 3.9.

I've updated the script by removing the `encoding=` param. Please try again.

**Comment by AlbeyAmakiir** [comment]
Ah! It seems to work now! Thankyou. :)
It does seem to list both my "now playing" and "previously played" entries as both individual "listens" of my tracks, but I assume that's more an issue on their end. Especially since the default in the config was to not share "now playing"s.

**Comment by vjeranc** [comment]
Yeah, if you mean listenbrainz, for some reason the now playing creates a scrobble. I would turn it off for listenbrainz.
